### ISSUE TITLE
The content of the poster cannot be turned into English after filling in

### ISSUE THREAD

**Issue by lvfangren** [Ovilia/acasia-poster#1]
**Steps to reproduce**
Fill in the poster in Chinese, then switch the button to English, and the content will not change.

**Expected**
The poster as a whole can be switched internationally

**Solutions**
Listen to the button change event, and then re-assign the attribute values ​​such as name, topic, title

**Comment by lvfangren** [comment]
Very good project, I have seen such a product demand. It would be great if it could support more functions (but it does not need to be a fully editable visual editor, that would be too complicated)

**Comment by Ovilia** [comment]
The UI will not be translated into English because the user of the original project are all Chinese. So it's not required.
If you have such requirement, you may fork this project and adapt it on your own.
Thanks!
